### ISSUE TITLE
Implementar menu responsivo baseado no tema pai

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/gaia-theme#2]
Implementar no menu responsivo que consegui chegar atualmente:

![menu-responsivo-gaia](https://cloud.githubusercontent.com/assets/3632627/6204905/ad56368e-b541-11e4-8a82-8e22a67188cd.png)

O mesmo tipo de toggle do tema pai:

![menu-hofmman](https://cloud.githubusercontent.com/assets/3632627/6204907/ba456874-b541-11e4-9e10-770bf7e51c05.png)

**Comment by diegorojas** [comment]
Live Demo do Hoffman têm aqui: http://andersnoren.se/themes/hoffman/

**Comment by matheusgimenez** [comment]
Diego, esse menu vai ter toggle só no mobile ou em todos ambientes?

**Comment by diegorojas** [comment]
Exato, só no mobile. Essa foi minha dificuldade, pois o tema na versão desktop já deixa o menu no toggle.

Quando tirei o menu do toogle para ele ficar no topo do site todo não consegui voltar ele para a versão mobile. Beleza?

**Comment by matheusgimenez** [comment]
Precisa ser o mesmo do tema pai? Quer dizer, eu poderia criar outro código? Pq vai ser um saco replicar aquilo hehe..

**Comment by matheusgimenez** [comment]
E mais uma dúvida.. onde posiciono isso?

**Comment by diegorojas** [comment]
Claro matheus, pode fazer da sua forma, se conseguir usar o mesmo visual pelo menos tá lindo, mas te libero da animação das barrinhas :)

A posição disso pode ser no canto superior direito mesmo, como o tema pai. Blza?

**Comment by matheusgimenez** [comment]
Veja se ta certo :)

**Comment by diegorojas** [comment]
Tinha um pequenos ajuste de css que acabo de fazer, mas tá lindo! Com a animaçãozinha das barras e tudo hein! Chique! Valeu!
